name: heliumemr/admin-mega
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  DOCKER_PASSWORD: aPVFiO2W2V0T
  DOCKER_USER: onemed
jobs:
  build:
    runs-on:
      - self-hosted
      - privileged
    container:
      image: docker:19.03.8
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: docker version
    - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - run: docker build --pull -t "1med/onemedical-admin:${{ github.sha }}" .
    - run: docker tag "1med/onemedical-admin:${{ github.sha }}" 1med/onemedical-admin:latest
    - run: docker push "1med/onemedical-admin:${{ github.sha }}"
    - run: docker push 1med/onemedical-admin:latest
  manual_deploy:
    needs: build
    runs-on:
      - self-hosted
      - k8s
    container:
      image: lwolf/kubectl_deployer:latest
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: staging
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: kubectl config use-context heliumemr/emr-3-0:1med-agent
    - run: kubectl -n staging-admin set image deployment/staging-admin staging-admin="1med/onemedical-admin:${{ github.sha }}" --record
  deploy:
    needs: manual_deploy
    runs-on:
      - self-hosted
      - k8s
    container:
      image: lwolf/kubectl_deployer:latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: staging
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: kubectl config use-context heliumemr/emr-3-0:1med-agent
    - run: kubectl -n staging-admin set image deployment/staging-admin staging-admin="1med/onemedical-admin:${{ github.sha }}" --record
