name: heliumemr/pdf-generator
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  DOCKER_USER: onemed
jobs:
  build-manual:
    runs-on:
      - self-hosted
      - privileged
    container:
      image: docker:latest
    if: github.event_name == 'workflow_dispatch'
    timeout-minutes: 60
    continue-on-error: true
    env:
      DOCKER_DRIVER: overlay2
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: docker version
    - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - run: docker build --pull -t "1med/pdf-generator:${{ github.sha }}" .
    - run: docker tag "1med/pdf-generator:${{ github.sha }}" 1med/pdf-generator:latest
    - run: docker push "1med/pdf-generator:${{ github.sha }}"
    - run: docker push 1med/pdf-generator:latest
    - run: docker image save -o pdf-generator.tar "1med/pdf-generator:${{ github.sha }}"
    - uses: actions/upload-artifact@v3.1.1
      if: success()
      with:
        name: "${{ github.job }}"
        retention-days: 7
        path: pdf-generator.tar
  build-auto:
    runs-on:
      - self-hosted
      - privileged
    container:
      image: docker:latest
    if: github.ref == 'refs/heads/master'
    timeout-minutes: 60
    env:
      DOCKER_DRIVER: overlay2
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: docker version
    - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - run: docker build --pull -t "1med/pdf-generator:${{ github.sha }}" .
    - run: docker tag "1med/pdf-generator:${{ github.sha }}" 1med/pdf-generator:latest
    - run: docker push "1med/pdf-generator:${{ github.sha }}"
    - run: docker push 1med/pdf-generator:latest
    - run: docker image save -o pdf-generator.tar "1med/pdf-generator:${{ github.sha }}"
    - uses: actions/upload-artifact@v3.1.1
      if: success()
      with:
        name: "${{ github.job }}"
        retention-days: 7
        path: pdf-generator.tar
  deploy-manual:
    needs:
    - build-manual
    - build-auto
    runs-on:
      - self-hosted
      - k8s
    container:
      image: lwolf/kubectl_deployer:latest
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: staging
    timeout-minutes: 60
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/download-artifact@v3.0.1
    - run: kubectl config use-context heliumemr/emr-3-0:1med-agent
    - run: kubectl -n pdf-generator-stg set image deployment pdf-generator-stg pdf-generator-stg="1med/pdf-generator:${{ github.sha }}" --record
  deploy-auto:
    needs:
    - build-manual
    - build-auto
    runs-on:
      - self-hosted
      - k8s
    container:
      image: lwolf/kubectl_deployer:latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: staging
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/download-artifact@v3.0.1
    - run: kubectl config use-context heliumemr/emr-3-0:1med-agent
    - run: kubectl -n pdf-generator-stg set image deployment pdf-generator-stg pdf-generator-stg="1med/pdf-generator:${{ github.sha }}" --record
