name: heliumemr/emr-3-0
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  DOCKER_USER: onemed
jobs:
  build-version:
    runs-on: ubuntu-latest
    container:
      image: docker:19.03.8
    timeout-minutes: 60
    env:
      DOCKER_DRIVER: overlay_fs
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: docker version
    - run: export VERSION=$(git rev-parse --short HEAD)
    - run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
    - run: docker build --pull -t "1med/emr3.0:${{ github.sha }}" .
    - run: docker push "1med/emr3.0:${{ github.sha }}"
  deploy-staging-auto:
    needs: build-version
    runs-on:
      - self-hosted
      - k8s
    container:
      image: lwolf/kubectl_deployer:latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: staging
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: kubectl config use-context heliumemr/emr-3-0:1med-agent
    - run: kubectl -n consolidated-emr30-staging set image deployment consolidated-emr30-staging consolidated-emr30-staging="1med/emr3.0:${{ github.sha }}" --record
  aks-staging-auto:
    needs: deploy-staging-auto
    runs-on:
      - self-hosted
      - k8s
    container:
      image: lwolf/kubectl_deployer:latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: consolidated-emr30-staging
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
        lfs: true
    - run: kubectl config get-contexts
    - run: kubectl config use-context heliumemr/emr-3-0:aks-agent
    - run: kubectl -n consolidated-emr-staging set image deployment consolidated-emr-staging consolidated-emr-staging="1med/emr3.0:${{ github.sha }}" --record
